

# This file was *autogenerated* from the file MissingModulus.sage
from sage.all_cmdline import *   # import sage library

import numpy as np

M = np.loadtxt('MissingModulus.txt', dtype=int)
print(M.shape)

lat = matrix(M)
reduction = lat.LLL()
print(reduction)

