import numpy as np
import socket
import json
import ast


M = np.loadtxt('lattice.txt', dtype=int)
# Using the same logic as in 'Nativity', we have to choose an offset
offset = 0
A = M[:-1].T[offset : offset + 512]
b = M[-1][offset : offset + 512]
e = np.loadtxt('e.txt', dtype=int)[0][offset : offset + 512]


print("A shape:", A.shape)
print("b shape:", b.shape)

S = np.linalg.solve(A,b-e)

HOST = "socket.cryptohack.org"
PORT = 13412 
# r = remote(HOST, PORT)

def json_recv(socket):
    line = socket.recv(200000)
    # For some reason, some responses are split into two lines, so I have to do this because only the first line is not a valid JSON.
    try:
        return json.loads(line)
    except:
        line += socket.recv(200000)
        return json.loads(line)

def json_send(socket, message):
    request = json.dumps(message).encode()
    socket.send(request)


flag = ''

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as socket:
    socket.connect((HOST, PORT))
    
    print(socket.recv(20000), "\n")

    # I made an early request with index = 10000 and the response was that the flag has length 46.
    l = 46
    for i in range(l):
        total = 0
        # Since b - A@S equals m*23 + e, we take a few samples to reduce the noise generated by the e's.
        # After 3 samples, the average of the values obtained should be very close to 23*m since the e is sampled as a normal, and therefore the expected value is 0.
        for _ in range(3):
            message = {
                'option': 'get_flag',
                'index': i
            }
            json_send(socket, message)
            response = json_recv(socket)
            # print(response)
            A = np.array(ast.literal_eval(response['A']), dtype=int)
            b = int(response['b'])
            total += b - A@S

        flag += chr(round(total/(3*23)))
        print(flag)

